# ============================================
# Railway Configuration - PrevLab (Root)
# ============================================
# Este arquivo está na RAIZ do repositório
# e configura o build do monorepo em simulador-atuarial-individual/
#
# Docs: https://docs.railway.app/deploy/config-as-code
# ============================================

[build]
# Usar Dockerfile na raiz do repositório
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
# Comando de inicialização
startCommand = "/app/start.sh"

# Health check
# Railway aguarda até 300s (5min) para o serviço ficar pronto
healthcheckPath = "/health"
healthcheckTimeout = 300
