version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prevlab-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/db/prevlab.db
      - LOG_LEVEL=info
      - WORKERS=1
      - CORS_ORIGINS=http://localhost,http://localhost:80,http://localhost:8000
    volumes:
      # Volume para persistir dados do SQLite
      - backend-data:/app/data
      # Volume para logs
      - backend-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - prevlab-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8000
    container_name: prevlab-frontend
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - prevlab-network

volumes:
  backend-data:
    driver: local
  backend-logs:
    driver: local

networks:
  prevlab-network:
    driver: bridge
