# ============================================
# Railway Configuration - PrevLab
# ============================================
# Docs: https://docs.railway.app/deploy/config-as-code
#
# IMPORTANTE - NOMENCLATURA DO PROJETO:
# - Nome sugerido do serviço: "prevlab"
# - Domínio gerado: prevlab-production.up.railway.app (ou similar)
# - Configure o nome no dashboard Railway durante criação do projeto
# - Ver docs/RAILWAY_SETUP_GUIDE.md para instruções detalhadas
#
# ============================================

[build]
# Usar Dockerfile customizado para Railway
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

# Context é a raiz do monorepo
buildContext = "."

[deploy]
# Comando de inicialização
startCommand = "/app/start.sh"

# Health check
healthcheckPath = "/health"
healthcheckTimeout = 10

[env]
# Variáveis de ambiente (podem ser sobrescritas no dashboard)
# Railway injeta automaticamente: PORT, RAILWAY_ENVIRONMENT, RAILWAY_PUBLIC_DOMAIN

# Backend
DATABASE_URL = "sqlite:///./data/db/prevlab.db"
LOG_LEVEL = "info"
WORKERS = "2"
PYTHONUNBUFFERED = "1"

# CORS - será configurado para aceitar domínio Railway
# Use ${RAILWAY_PUBLIC_DOMAIN} no dashboard para configurar dinamicamente

[volumes]
# Volume persistente para SQLite
# Atenção: Deve ser criado manualmente no dashboard Railway
# Path: /app/data
# Size: 1GB (mínimo recomendado)
