services:
  # Backend Service
  - type: web
    name: prevlab-backend
    runtime: python
    env: python
    buildCommand: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      export PATH="$HOME/.cargo/bin:$PATH"
      cd backend
      uv pip install --system -r pyproject.toml
    startCommand: cd backend && uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///./data/db/prevlab.db
      - key: LOG_LEVEL
        value: info
      - key: WORKERS
        value: 1
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: prevlab-frontend
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /health
    disk:
      name: prevlab-data
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1
    plan: starter

  # Frontend Service
  - type: web
    name: prevlab-frontend
    runtime: static
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: prevlab-backend
          envVarKey: RENDER_EXTERNAL_URL
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: "1; mode=block"
    routes:
      - type: rewrite
        source: /api/*
        destination: https://prevlab-backend.onrender.com/*
      - type: rewrite
        source: /*
        destination: /index.html
    plan: starter
